# -*- coding: utf-8 -*-
"""week3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PjTJCWpZ4ZvuSjF5884DrWpeI_k-SuUU
"""

# ==========================================================
# WEEK 3 - LINEAR REGRESSION USING GRADIENT DESCENT
# ==========================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression


# ==========================================================
# 1. LOAD DATASET
# ==========================================================

df = pd.read_csv("placement_predict_50k_adjusted.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

print("\nFirst 5 rows:")
display(df.head())


# ==========================================================
# 2. CHECK COLUMNS
# ==========================================================

print("\nColumn names:")
print(df.columns.tolist())


# ==========================================================
# 3. TARGET COLUMN
# ==========================================================

target_col = "CGPA"

if target_col not in df.columns:
    raise ValueError(
        f"'{target_col}' column was not found in the dataset."
    )


# ==========================================================
# 4. SELECT FEATURES
# ==========================================================

sgpa_cols = [f"SGPA_Sem{i}" for i in range(1, 9)]

drop_cols = [
    target_col,
    "StudentID",
    "CGPA_Tier"
] + sgpa_cols

# Drop only columns that actually exist
drop_cols = [c for c in drop_cols if c in df.columns]

feature_df = df.drop(columns=drop_cols)

# Keep only numerical columns
feature_df = feature_df.select_dtypes(
    include=[np.number]
)


# ==========================================================
# 5. HANDLE MISSING VALUES
# ==========================================================

feature_df = feature_df.fillna(
    feature_df.median(numeric_only=True)
)

print("\nNumber of features:", feature_df.shape[1])

print("\nFeatures used:")
print(feature_df.columns.tolist())


# ==========================================================
# 6. CREATE X AND y
# ==========================================================

X = feature_df.values
y = df[target_col].values.reshape(-1, 1)


print("\nX shape:", X.shape)
print("y shape:", y.shape)


# ==========================================================
# 7. TRAIN / TEST SPLIT
# ==========================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("\nTraining samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])


# ==========================================================
# 8. FEATURE SCALING
# ==========================================================

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# ==========================================================
# 9. ADD BIAS COLUMN
# ==========================================================

X_train_b = np.c_[
    np.ones((X_train.shape[0], 1)),
    X_train
]

X_test_b = np.c_[
    np.ones((X_test.shape[0], 1)),
    X_test
]


# ==========================================================
# 10. GRADIENT DESCENT FUNCTION
# ==========================================================

def gradient_descent(
    X,
    y,
    lr=0.01,
    n_iters=1000
):

    m, n = X.shape

    theta = np.zeros((n, 1))

    losses = []

    for i in range(n_iters):

        # Prediction
        y_pred = X @ theta

        # Error
        error = y_pred - y

        # Mean Squared Error
        loss = (1 / (2 * m)) * np.sum(error ** 2)

        losses.append(loss)

        # Gradient
        gradient = (1 / m) * (X.T @ error)

        # Update weights
        theta = theta - lr * gradient

        # Print progress
        if i % 100 == 0:
            print(
                f"Iteration {i:4d} | Loss: {loss:.6f}"
            )

    return theta, losses


#